# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/michael/Desktop/cam84_development/cam84_updates

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/michael/Desktop/cam84_development/cam84_updates

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/michael/Desktop/cam84_development/cam84_updates/CMakeFiles /home/michael/Desktop/cam84_development/cam84_updates/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/michael/Desktop/cam84_development/cam84_updates/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named cam84

# Build rule for target.
cam84: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cam84
.PHONY : cam84

# fast build rule for target.
cam84/fast:
	$(MAKE) -f CMakeFiles/cam84.dir/build.make CMakeFiles/cam84.dir/build
.PHONY : cam84/fast

#=============================================================================
# Target rules for targets named indi_cam84_ccd

# Build rule for target.
indi_cam84_ccd: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 indi_cam84_ccd
.PHONY : indi_cam84_ccd

# fast build rule for target.
indi_cam84_ccd/fast:
	$(MAKE) -f CMakeFiles/indi_cam84_ccd.dir/build.make CMakeFiles/indi_cam84_ccd.dir/build
.PHONY : indi_cam84_ccd/fast

# target to build an object file
cam84_ccd.o:
	$(MAKE) -f CMakeFiles/indi_cam84_ccd.dir/build.make CMakeFiles/indi_cam84_ccd.dir/cam84_ccd.o
.PHONY : cam84_ccd.o

# target to preprocess a source file
cam84_ccd.i:
	$(MAKE) -f CMakeFiles/indi_cam84_ccd.dir/build.make CMakeFiles/indi_cam84_ccd.dir/cam84_ccd.i
.PHONY : cam84_ccd.i

# target to generate assembly for a file
cam84_ccd.s:
	$(MAKE) -f CMakeFiles/indi_cam84_ccd.dir/build.make CMakeFiles/indi_cam84_ccd.dir/cam84_ccd.s
.PHONY : cam84_ccd.s

# target to build an object file
libcam84.o:
	$(MAKE) -f CMakeFiles/cam84.dir/build.make CMakeFiles/cam84.dir/libcam84.o
.PHONY : libcam84.o

# target to preprocess a source file
libcam84.i:
	$(MAKE) -f CMakeFiles/cam84.dir/build.make CMakeFiles/cam84.dir/libcam84.i
.PHONY : libcam84.i

# target to generate assembly for a file
libcam84.s:
	$(MAKE) -f CMakeFiles/cam84.dir/build.make CMakeFiles/cam84.dir/libcam84.s
.PHONY : libcam84.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... install/local"
	@echo "... cam84"
	@echo "... list_install_components"
	@echo "... indi_cam84_ccd"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... install"
	@echo "... cam84_ccd.o"
	@echo "... cam84_ccd.i"
	@echo "... cam84_ccd.s"
	@echo "... libcam84.o"
	@echo "... libcam84.i"
	@echo "... libcam84.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

